In [1]:
import pandas as pd
import numpy as np

# A practical guide to Singular Value Decomposition in Python

Recommender systems have become increasingly popular in recent years, and are used by some of the largest websites in the world to predict the likelihood of a user taking an action on an item. In the world of Netflix, this means recommending similar movies to the ones you have seen. In the world of dating, this means suggesting matches similar to people you already showed interest in!

My path to recommenders has been an unusual one: from a Software Engineer to working on matching algorithms at a dating company, with a little background on machine learning. With my knowledge of Python and the use of basic SVD (Singular Value Decomposition) frameworks, I was able to understand SVDs from a practical standpoint of what you can do with them, instead of focusing on the science.

In my talk, you will learn 2 practical ways of generating recommendations using SVDs: matrix factorization and item similarity. We will be learning the high-level components of SVD the "doer way": we will be implementing a simple movie recommendation engine with the help of Jupiter notebooks, the MovieLens database, and the Surprise recommendation package.

## Indice

 - Downloading and exploring the MovieLens dataset
 - ROC Curve

In [2]:
movie_data_columns = [
    'movie_id', 'title', 'release_date', 'video_release_date', 'url',
    'unknown', 'Action', 'Adventure', 'Animation', "Children's",
    'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir',
    'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller',
    'War', 'Western'
]

movie_data = pd.read_csv(
    'datasets/ml-100k/u.item', 
    sep = '|', 
    encoding = "ISO-8859-1", 
    header = None, 
    names = movie_data_columns,
    index_col = 'movie_id'
)
movie_data['release_date'] = pd.to_datetime(movie_data['release_date'])

In [3]:
ratings_data = pd.read_csv(
    'datasets/ml-100k/u.data',
    sep = '\t',
    encoding = "ISO-8859-1",
    header = None,
    names=['user_id', 'movie_id', 'rating', 'timestamp']
)
ratings_data.head(10)

   user_id  movie_id  rating  timestamp
0      196       242       3  881250949
1      186       302       3  891717742
2       22       377       1  878887116
3      244        51       2  880606923
4      166       346       1  886397596
5      298       474       4  884182806
6      115       265       2  881171488
7      253       465       5  891628467
8      305       451       3  886324817
9        6        86       3  883603013

## Explanation of the above table

- User **196** rated movie **242** with a score of **3** 
- User **186** rated movie **302** with a score of **3** 
- User **22** rated movie **377** with a score of **3**

In [7]:
ratings_data[ratings_data['movie_id'] == 242]['rating'].describe()

count    117.000000
mean       3.991453
std        0.995643
min        1.000000
25%        4.000000
50%        4.000000
75%        5.000000
max        5.000000
Name: rating, dtype: float64

In [14]:

movie_data.loc[242]

title                                                    Kolya (1996)
release_date                                      1997-01-24 00:00:00
video_release_date                                                NaN
url                   http://us.imdb.com/M/title-exact?Kolya%20(1996)
unknown                                                             0
Action                                                              0
Adventure                                                           0
Animation                                                           0
Children's                                                          0
Comedy                                                              1
Crime                                                               0
Documentary                                                         0
Drama                                                               0
Fantasy                                                             0
Film-Noir                                                           0
Horror                                                              0
Musical                                                             0
Mystery                                                             0
Romance                                                             0
Sci-Fi                                                              0
Thriller                                                            0
War                                                                 0
Western                                                             0
Name: 242, dtype: object

In [41]:
from abc import ABC, abstractmethod
from typing import List


class BaseRecommender(ABC):
    
    @abstractmethod
    def predict_for_user(self, user_id: int, n: int) -> List[str]:
        ...



class RandomRecommender(BaseRecommender):
    
    def __init__(self, ratings: pd.DataFrame, movies: pd.DataFrame) -> None:
        self.ratings = ratings
        self.movies = movies
    
    def predict_for_user(self, user_id: int, n: int) -> List[str]:
        
        # Get all movies seen by user
        movies_seen_by_user = self.ratings[self.ratings['user_id'] == user_id]['movie_id']
        
        # Get all movies, and remove the ones seen by the user
        movies_not_seen_by_user: pd.DataFrame = movie_data[~movie_data.index.isin(movies_seen_by_user)]
            
        # Return a random sample of N films
        return list(movies_not_seen_by_user.sample(n)['title'])
        

        
random_recommender = RandomRecommender(ratings_data, movie_data)
print(random_recommender.predict_for_user(186, 5))

['Big Green, The (1995)', 'Ed Wood (1994)', 'Alphaville (1965)', 'Apple Dumpling Gang, The (1975)', 'Bullets Over Broadway (1994)']

In [61]:
from surprise import SVD
from surprise import Dataset
from surprise.model_selection import cross_validate, train_test_split


data = Dataset.load_builtin('ml-100k')
trainset, testset = train_test_split(data, test_size=.25)

model = SVD()
model.fit(trainset)

In [80]:


class MatrixFactorizationRecommender(BaseRecommender):
    
    def __init__(self, ratings: pd.DataFrame, movies: pd.DataFrame, svd: SVD) -> None:
        self.svd = svd
        self.ratings = ratings
        self.movies = movies
    
    def predict_for_user(self, user_id: int, n: int) -> List[str]:
        
        # Get all movies seen by user
        movies_seen_by_user = self.ratings[self.ratings['user_id'] == user_id]['movie_id']
        
        # Get all movies, and remove the ones seen by the user
        movies_not_seen_by_user: pd.DataFrame = movie_data[~movie_data.index.isin(movies_seen_by_user)]
            
            
        def _inner_predict(idx):
            return self.svd.predict(str(user_id), str(idx)).est
        
        movies_not_seen_by_user['score'] = movies_not_seen_by_user.index.map(_inner_predict)
        return movies_not_seen_by_user.sort_values('score', ascending=False).iloc[:n][['title', 'score']]

random_recommender = MatrixFactorizationRecommender(ratings_data, movie_data, model)
random_recommender.predict_for_user(186, 5)

/Users/danielpyrathon/anaconda3/envs/pycon/lib/python3.6/site-packages/ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

                                           title     score
movie_id
483                            Casablanca (1942)  4.908095
357       One Flew Over the Cuckoo's Nest (1975)  4.664586
272                     Good Will Hunting (1997)  4.622444
479                               Vertigo (1958)  4.579681
96             Terminator 2: Judgment Day (1991)  4.570107

In [77]:
model.predict(186, 242)

model.trainset._raw2inner_id_users

{'1': 442,
 '10': 23,
 '100': 573,
 '101': 141,
 '102': 287,
 '103': 855,
 '104': 399,
 '105': 474,
 '106': 808,
 '107': 335,
 '108': 598,
 '109': 229,
 '11': 60,
 '110': 314,
 '111': 906,
 '112': 325,
 '113': 515,
 '114': 418,
 '115': 587,
 '116': 116,
 '117': 35,
 '118': 447,
 '119': 382,
 '12': 709,
 '120': 908,
 '121': 788,
 '122': 626,
 '123': 685,
 '124': 811,
 '125': 166,
 '126': 269,
 '127': 311,
 '128': 517,
 '129': 797,
 '13': 159,
 '130': 86,
 '131': 915,
 '132': 752,
 '133': 338,
 '134': 643,
 '135': 620,
 '136': 695,
 '137': 479,
 '138': 624,
 '139': 611,
 '14': 243,
 '140': 640,
 '141': 175,
 '142': 688,
 '143': 368,
 '144': 150,
 '145': 220,
 '146': 936,
 '147': 875,
 '148': 604,
 '149': 546,
 '15': 29,
 '150': 537,
 '151': 323,
 '152': 318,
 '153': 762,
 '154': 776,
 '155': 365,
 '156': 234,
 '157': 634,
 '158': 226,
 '159': 184,
 '16': 485,
 '160': 162,
 '161': 772,
 '162': 769,
 '163': 16,
 '164': 632,
 '165': 764,
 '166': 478,
 '167': 122,
 '168': 791,
 '169': 584,
 '17': 864,
 '170': 907,
 '171': 868,
 '172': 254,
 '173': 383,
 '174': 65,
 '175': 642,
 '176': 707,
 '177': 499,
 '178': 305,
 '179': 782,
 '18': 136,
 '180': 729,
 '181': 218,
 '182': 459,
 '183': 71,
 '184': 191,
 '185': 859,
 '186': 111,
 '187': 371,
 '188': 398,
 '189': 50,
 '19': 667,
 '190': 683,
 '191': 70,
 '192': 854,
 '193': 728,
 '194': 114,
 '195': 7,
 '196': 717,
 '197': 561,
 '198': 559,
 '199': 755,
 '2': 813,
 '20': 550,
 '200': 1,
 '201': 295,
 '202': 521,
 '203': 673,
 '204': 696,
 '205': 732,
 '206': 308,
 '207': 85,
 '208': 495,
 '209': 807,
 '21': 233,
 '210': 435,
 '211': 833,
 '212': 416,
 '213': 93,
 '214': 237,
 '215': 583,
 '216': 656,
 '217': 446,
 '218': 692,
 '219': 775,
 '22': 380,
 '220': 756,
 '221': 102,
 '222': 293,
 '223': 240,
 '224': 490,
 '225': 912,
 '226': 630,
 '227': 148,
 '228': 589,
 '229': 526,
 '23': 38,
 '230': 452,
 '231': 917,
 '232': 351,
 '233': 487,
 '234': 152,
 '235': 263,
 '236': 373,
 '237': 660,
 '238': 63,
 '239': 264,
 '24': 278,
 '240': 590,
 '241': 596,
 '242': 738,
 '243': 431,
 '244': 52,
 '245': 878,
 '246': 481,
 '247': 428,
 '248': 224,
 '249': 699,
 '25': 275,
 '250': 62,
 '251': 576,
 '252': 881,
 '253': 180,
 '254': 659,
 '255': 51,
 '256': 104,
 '257': 25,
 '258': 921,
 '259': 712,
 '26': 437,
 '260': 668,
 '261': 909,
 '262': 316,
 '263': 273,
 '264': 528,
 '265': 902,
 '266': 886,
 '267': 301,
 '268': 356,
 '269': 202,
 '27': 814,
 '270': 235,
 '271': 310,
 '272': 567,
 '273': 913,
 '274': 513,
 '275': 81,
 '276': 177,
 '277': 562,
 '278': 444,
 '279': 103,
 '28': 43,
 '280': 0,
 '281': 768,
 '282': 938,
 '283': 337,
 '284': 370,
 '285': 90,
 '286': 183,
 '287': 839,
 '288': 206,
 '289': 276,
 '29': 899,
 '290': 405,
 '291': 300,
 '292': 73,
 '293': 172,
 '294': 713,
 '295': 55,
 '296': 190,
 '297': 575,
 '298': 647,
 '299': 37,
 '3': 322,
 '30': 849,
 '300': 588,
 '301': 124,
 '302': 579,
 '303': 59,
 '304': 354,
 '305': 330,
 '306': 829,
 '307': 434,
 '308': 39,
 '309': 553,
 '31': 725,
 '310': 774,
 '311': 486,
 '312': 78,
 '313': 266,
 '314': 216,
 '315': 897,
 '316': 228,
 '317': 888,
 '318': 421,
 '319': 905,
 '32': 297,
 '320': 375,
 '321': 407,
 '322': 46,
 '323': 556,
 '324': 41,
 '325': 396,
 '326': 599,
 '327': 106,
 '328': 113,
 '329': 48,
 '33': 533,
 '330': 182,
 '331': 386,
 '332': 440,
 '333': 718,
 '334': 236,
 '335': 347,
 '336': 189,
 '337': 926,
 '338': 536,
 '339': 26,
 '34': 789,
 '340': 761,
 '341': 929,
 '342': 621,
 '343': 161,
 '344': 613,
 '345': 529,
 '346': 425,
 '347': 79,
 '348': 363,
 '349': 662,
 '35': 705,
 '350': 766,
 '351': 711,
 '352': 593,
 '353': 911,
 '354': 45,
 '355': 665,
 '356': 740,
 '357': 690,
 '358': 572,
 '359': 935,
 '36': 882,
 '360': 248,
 '361': 560,
 '362': 525,
 '363': 169,
 '364': 783,
 '365': 867,
 '366': 828,
 '367': 670,
 '368': 260,
 '369': 697,
 '37': 6,
 '370': 128,
 '371': 605,
 '372': 694,
 '373': 97,
 '374': 317,
 '375': 615,
 '376': 600,
 '377': 777,
 '378': 28,
 '379': 105,
 '38': 179,
 '380': 77,
 '381': 329,
 '382': 606,
 '383': 577,
 '384': 555,
 '385': 94,
 '386': 715,
 '387': 387,
 '388': 460,
 '389': 57,
 '39': 834,
 '390': 488,
 '391': 82,
 '392': 261,
 '393': 198,
 '394': 520,
 '395': 288,
 '396': 130,
 '397': 246,
 '398': 204,
 '399': 209,
 '4': 541,
 '40': 822,
 '400': 798,
 '401': 291,
 '402': 799,
 '403': 457,
 '404': 414,
 '405': 56,
 '406': 245,
 '407': 343,
 '408': 914,
 '409': 299,
 '41': 424,
 '410': 730,
 '411': 448,
 '412': 787,
 '413': 781,
 '414': 619,
 '415': 535,
 '416': 344,
 '417': 12,
 '418': 942,
 '419': 153,
 '42': 543,
 '420': 524,
 '421': 49,
 '422': 279,
 '423': 865,
 '424': 99,
 '425': 623,
 '426': 780,
 '427': 853,
 '428': 704,
 '429': 139,
 '43': 411,
 '430': 676,
 '431': 877,
 '432': 477,
 '433': 133,
 '434': 741,
 '435': 262,
 '436': 167,
 '437': 681,
 '438': 669,
 '439': 830,
 '44': 40,
 '440': 284,
 '441': 413,
 '442': 455,
 '443': 931,
 '444': 941,
 '445': 10,
 '446': 824,
 '447': 219,
 '448': 846,
 '449': 67,
 '45': 735,
 '450': 9,
 '451': 512,
 '452': 333,
 '453': 195,
 '454': 42,
 '455': 563,
 '456': 163,
 '457': 341,
 '458': 272,
 '459': 187,
 '46': 734,
 '460': 118,
 '461': 870,
 '462': 800,
 '463': 404,
 '464': 503,
 '465': 360,
 '466': 594,
 '467': 211,
 '468': 225,
 '469': 591,
 '47': 876,
 '470': 76,
 '471': 851,
 '472': 11,
 '473': 511,
 '474': 230,
 '475': 765,
 '476': 364,
 '477': 658,
 '478': 200,
 '479': 217,
 '48': 747,
 '480': 244,
 '481': 501,
 '482': 8,
 '483': 519,
 '484': 361,
 '485': 98,
 '486': 2,
 '487': 258,
 '488': 292,
 '489': 385,
 '49': 80,
 '490': 809,
 '491': 923,
 '492': 760,
 '493': 66,
 '494': 551,
 '495': 449,
 '496': 290,
 '497': 366,
 '498': 426,
 '499': 20,
 '5': 196,
 '50': 165,
 '500': 75,
 '501': 895,
 '502': 283,
 '503': 412,
 '504': 427,
 '505': 827,
 '506': 120,
 '507': 622,
 '508': 342,
 '509': 856,
 '51': 566,
 '510': 845,
 '511': 516,
 '512': 635,
 '513': 617,
 '514': 181,
 '515': 629,
 '516': 138,
 '517': 429,
 '518': 826,
 '519': 100,
 '52': 794,
 '520': 742,
 '521': 677,
 '522': 698,
 '523': 313,
 '524': 21,
 '525': 268,
 '526': 253,
 '527': 509,
 '528': 58,
 '529': 13,
 '53': 898,
 '530': 397,
 '531': 932,
 '532': 638,
 '533': 72,
 '534': 578,
 '535': 274,
 '536': 135,
 '537': 185,
 '538': 607,
 '539': 548,
 '54': 441,
 '540': 476,
 '541': 348,
 '542': 496,
 '543': 406,
 '544': 850,
 '545': 312,
 '546': 355,
 '547': 492,
 '548': 439,
 '549': 922,
 '55': 648,
 '550': 661,
 '551': 326,
 '552': 639,
 '553': 505,
 '554': 649,
 '555': 564,
 '556': 508,
 '557': 539,
 '558': 126,
 '559': 463,
 '56': 518,
 '560': 107,
 '561': 171,
 '562': 345,
 '563': 475,
 '564': 549,
 '565': 603,
 '566': 530,
 '567': 403,
 '568': 569,
 '569': 654,
 '57': 213,
 '570': 934,
 '571': 818,
 '572': 706,
 '573': 751,
 '574': 866,
 '575': 880,
 '576': 887,
 '577': 129,
 '578': 737,
 '579': 837,
 '58': 207,
 '580': 402,
 '581': 651,
 '582': 557,
 '583': 810,
 '584': 257,
 '585': 227,
 '586': 255,
 '587': 680,
 '588': 149,
 '589': 835,
 '59': 158,
 '590': 534,
 '591': 378,
 '592': 74,
 '593': 510,
 '594': 793,
 '595': 430,
 '596': 64,
 '597': 340,
 '598': 884,
 '599': 675,
 '6': 151,
 '60': 143,
 '600': 456,
 '601': 315,
 '602': 514,
 '603': 391,
 '604': 570,
 '605': 597,
 '606': 346,
 '607': 687,
 '608': 154,
 '609': 465,
 '61': 939,
 '610': 96,
 '611': 767,
 '612': 500,
 '613': 674,
 '614': 445,
 '615': 95,
 '616': 298,
 '617': 221,
 '618': 208,
 '619': 422,
 '62': 493,
 '620': 744,
 '621': 480,
 '622': 307,
 '623': 666,
 '624': 438,
 '625': 285,
 '626': 904,
 '627': 249,
 '628': 552,
 '629': 353,
 '63': 464,
 '630': 324,
 '631': 610,
 '632': 841,
 '633': 280,
 '634': 194,
 '635': 628,
 '636': 889,
 '637': 53,
 '638': 168,
 '639': 633,
 '64': 409,
 '640': 586,
 '641': 896,
 '642': 88,
 '643': 4,
 '644': 893,
 '645': 281,
 '646': 686,
 '647': 784,
 '648': 121,
 '649': 724,
 '65': 443,
 '650': 134,
 '651': 745,
 '652': 763,
 '653': 186,
 '654': 33,
 '655': 214,
 '656': 568,
 '657': 786,
 '658': 636,
 '659': 176,
 '66': 357,
 '660': 592,
 '661': 436,
 '662': 178,
 '663': 321,
 '664': 415,
 '665': 119,
 '666': 112,
 '667': 601,
 '668': 901,
 '669': 595,
 '67': 602,
 '670': 721,
 '671': 393,
 '672': 748,
 '673': 733,
 '674': 778,
 '675': 910,
 '676': 719,
 '677': 472,
 '678': 806,
 '679': 108,
 '68': 527,
 '680': 491,
 '681': 817,
 '682': 147,
 '683': 664,
 '684': 395,
 '685': 812,
 '686': 672,
 '687': 743,
 '688': 682,
 '689': 458,
 '69': 146,
 '690': 523,
 '691': 473,
 '692': 259,
 '693': 137,
 '694': 547,
 '695': 804,
 '696': 924,
 '697': 631,
 '698': 267,
 '699': 145,
 '7': 91,
 '70': 271,
 '700': 795,
 '701': 860,
 '702': 702,
 '703': 142,
 '704': 653,
 '705': 468,
 '706': 417,
 '707': 193,
 '708': 750,
 '709': 453,
 '71': 838,
 '710': 296,
 '711': 470,
 '712': 374,
 '713': 408,
 '714': 369,
 '715': 367,
 '716': 160,
 '717': 170,
 '718': 710,
 '719': 796,
 '72': 83,
 '720': 388,
 '721': 205,
 '722': 757,
 '723': 381,
 '724': 304,
 '725': 779,
 '726': 558,
 '727': 24,
 '728': 918,
 '729': 940,
 '73': 466,
 '730': 873,
 '731': 282,
 '732': 930,
 '733': 174,
 '734': 571,
 '735': 451,
 '736': 861,
 '737': 831,
 '738': 69,
 '739': 727,
 '74': 522,
 '740': 614,
 '741': 306,
 '742': 773,
 '743': 726,
 '744': 693,
 '745': 637,
 '746': 689,
 '747': 32,
 '748': 701,
 '749': 164,
 '75': 582,
 '750': 400,
 '751': 410,
 '752': 87,
 '753': 847,
 '754': 872,
 '755': 545,
 '756': 328,
 '757': 327,
 '758': 377,
 '759': 892,
 '76': 247,
 '760': 758,
 '761': 644,
 '762': 790,
 '763': 394,
 '764': 332,
 '765': 132,
 '766': 507,
 '767': 844,
 '768': 36,
 '769': 857,
 '77': 869,
 '770': 497,
 '771': 739,
 '772': 933,
 '773': 265,
 '774': 101,
 '775': 201,
 '776': 157,
 '777': 506,
 '778': 691,
 '779': 646,
 '78': 802,
 '780': 469,
 '781': 805,
 '782': 331,
 '783': 842,
 '784': 504,
 '785': 937,
 '786': 498,
 '787': 657,
 '788': 289,
 '789': 554,
 '79': 358,
 '790': 92,
 '791': 858,
 '792': 419,
 '793': 420,
 '794': 350,
 '795': 203,
 '796': 212,
 '797': 925,
 '798': 155,
 '799': 467,
 '8': 627,
 '80': 723,
 '800': 863,
 '801': 585,
 '802': 54,
 '803': 852,
 '804': 44,
 '805': 34,
 '806': 188,
 '807': 84,
 '808': 423,
 '809': 250,
 '81': 320,
 '810': 652,
 '811': 746,
 '812': 339,
 '813': 565,
 '814': 716,
 '815': 372,
 '816': 489,
 '817': 720,
 '818': 891,
 '819': 903,
 '82': 302,
 '820': 916,
 '821': 27,
 '822': 885,
 '823': 222,
 '824': 843,
 '825': 199,
 '826': 771,
 '827': 920,
 '828': 352,
 '829': 454,
 '83': 494,
 '830': 309,
 '831': 19,
 '832': 900,
 '833': 540,
 '834': 821,
 '835': 753,
 '836': 840,
 '837': 759,
 '838': 736,
 '839': 379,
 '84': 483,
 '840': 31,
 '841': 785,
 '842': 618,
 '843': 544,
 '844': 532,
 '845': 836,
 '846': 127,
 '847': 580,
 '848': 336,
 '849': 239,
 '85': 14,
 '850': 678,
 '851': 89,
 '852': 890,
 '853': 215,
 '854': 197,
 '855': 3,
 '856': 708,
 '857': 883,
 '858': 625,
 '859': 612,
 '86': 684,
 '860': 192,
 '861': 919,
 '862': 68,
 '863': 349,
 '864': 334,
 '865': 471,
 '866': 484,
 '867': 390,
 '868': 140,
 '869': 531,
 '87': 241,
 '870': 232,
 '871': 450,
 '872': 609,
 '873': 815,
 '874': 792,
 '875': 359,
 '876': 123,
 '877': 803,
 '878': 15,
 '879': 832,
 '88': 641,
 '880': 616,
 '881': 251,
 '882': 144,
 '883': 156,
 '884': 376,
 '885': 608,
 '886': 18,
 '887': 125,
 '888': 874,
 '889': 432,
 '89': 384,
 '890': 210,
 '891': 671,
 '892': 679,
 '893': 270,
 '894': 231,
 '895': 722,
 '896': 319,
 '897': 252,
 '898': 754,
 '899': 17,
 '9': 801,
 '90': 238,
 '900': 879,
 '901': 110,
 '902': 581,
 '903': 109,
 '904': 823,
 '905': 871,
 '906': 714,
 '907': 362,
 '908': 389,
 '909': 820,
 '91': 502,
 '910': 433,
 '911': 131,
 '912': 749,
 '913': 286,
 '914': 894,
 '915': 928,
 '916': 294,
 '917': 862,
 '918': 462,
 '919': 277,
 '92': 47,
 '920': 663,
 '921': 574,
 '922': 242,
 '923': 173,
 '924': 848,
 '925': 650,
 '926': 655,
 '927': 256,
 '928': 461,
 '929': 819,
 '93': 700,
 '930': 5,
 '931': 115,
 '932': 61,
 '933': 816,
 '934': 30,
 '935': 703,
 '936': 223,
 '937': 825,
 '938': 731,
 '939': 645,
 '94': 117,
 '940': 770,
 '941': 927,
 '942': 22,
 '943': 303,
 '95': 401,
 '96': 542,
 '97': 538,
 '98': 392,
 '99': 482}